# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: SB Tech Blog
email: sunbiny77@naver.com
description: > # 여러 줄 설명을 위한 설정
  This is my blog where I share my knowledge and experience in the field of technology.
baseurl: "" # 사이트가 루트가 아닌 하위 디렉토리에 있을 경우 설정 (예: /blog)
url: "https://vincent8-8.github.io" # 사이트의 기본 URL

# Build settings
markdown: kramdown
theme: minima # Jekyll 테마
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks 설정
permalink: /:categories/:year/:month/:day/:title/

# Social settings
github_username: vincent8-8
instagram_username: yiiiisb8.8

# Pagination 설정
paginate: 5
paginate_path: "/page/:num/"

# Exclude files and directories from processing
exclude:
  - node_modules
  - vendor/bundle

# Include specific files
include:
  - _pages

# Custom variables
author:
  name: "Sunbin Yi"
  bio: "Tech enthusiast and software developer."
  location: "Seoul, South Korea"
  gravatar: "your-gravatar-url"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sunbin Yi"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Sunbin Yi"

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# SEO settings
seo:
  title: "SB Tech Blog"
  description: "Sharing knowledge and experience in technology."
  author: "Sunbin Yi"
  twitter_username: "your_twitter_username"

# Sitemap settings
sitemap:
  changefreq: weekly
  priority: 0.7

# Minima theme settings (추가 설정이 가능하다면)
minima:
  social_links:
    twitter: "https://twitter.com/your_twitter_username"
    github: "https://github.com/vincent8-8"
    instagram: "https://www.instagram.com/yiiiisb8.8"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
